/*
 * arch/blackfin/include/asm/mach-bf548/BF542_def.h
 *
 * Copyright (c) 2016 Allwinnertech Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 */
/* DO NOT EDIT THIS FILE
 * Automatically generated by generate-def-headers.xsl
 * DO NOT EDIT THIS FILE
 */

#ifndef __BFIN_DEF_ADSP_BF542_proc__
#define __BFIN_DEF_ADSP_BF542_proc__

#include "../mach-common/ADSP-EDN-core_def.h"

#include "ADSP-EDN-BF542-extended_def.h"

#define CHIPID                         0xFFC00014
#define SWRST                          0xFFC00100 /* Software Reset Register */
#define SYSCR                          0xFFC00104 /* System Configuration register */

#endif /* __BFIN_DEF_ADSP_BF542_proc__ */
